name: RAUM3
favicon: null
layout_spectrum: 0.25091
typography_spectrum: 0.49244
title: 'RAUM3 | print.web.mobile.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ec7f22'
    - '#168dc7'
    - '#73bcde'
    - '#f9d4b1'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
